coffee -c include.coffee
coffee -c fbremix.coffee
coffee -c caching/cache.coffee
coffee -c modes/remixmode.coffee
coffee -c modes/browse/browsemode.coffee
coffee -c modes/browse/wallview.coffee
coffee -c styling/stylist.coffee
coffee -c styling/normalstylist.coffee
coffee -c streams/stream.coffee
coffee -c streams/feed.coffee
